### ISSUE TITLE
getState功能

### ISSUE THREAD

**Issue by wangmingxu** [beizhedenglong/mini-context-store#1]
能不能提供一个store.getState()方法来获取store的值？

**Comment by beizhedenglong** [comment]
我是觉得没有必要。你可以在 action 以及 consumer children 中通过传入的参数取得当前state。
`action: (args) => state => {}`
`<Consumer>{(state, actions) => {}}<Consumer />`

**Comment by wangmingxu** [comment]
我觉得还是有应用场景的，比如在服务端渲染时同步store到客户端
